# system-update
- src: git+https://github.com/ttych/ansible_role_system-update.git
  version: master
  name: system-update

- src: git+https://github.com/ttych/ansible_role_dotfiles.git
  version: master
  name: dotfiles

- src: git+https://github.com/ttych/ansible_role_base_system.git
  version: master
  name: base_system

- src: git+https://github.com/ttych/ansible_role_packages.git
  version: master
  name: packages

- src: git@github.com:ttych/ansible_role_zaton_users.git
  scm: git
  version: master
  name: zaton_users

- src: git+https://github.com/ttych/ansible_role_zdata.git
  version: master
  name: zdata

- src: git+https://github.com/ttych/ansible_role_zshare.git
  version: master
  name: zshare

- src: git+https://github.com/ttych/ansible_role_efibootmgr-hack.git
  version: master
  name: efibootmgr-hack

- src: git+https://github.com/ttych/ansible_role_services.git
  version: master
  name: services

- src: git+https://github.com/ttych/ansible_role_daemontools.git
  version: master
  name: daemontools

- src: git+https://github.com/ttych/ansible_role_dhcpd.git
  version: master
  name: dhcpd

- src: git+https://github.com/ttych/ansible_role_network.git
  version: master
  name: network
