# system-update
- src: https://github.com/ttych/ansible_role_system-update.git
  version: master
  name: system-update

- src: https://github.com/ttych/ansible_role_dotfiles.git
  version: master
  name: dotfiles

- src: https://github.com/ttych/ansible_role_base_system.git
  version: master
  name: base_system

- src: https://github.com/ttych/ansible_role_packages.git
  version: master
  name: packages

- src: git@github.com:ttych/ansible_role_zaton_users.git
  scm: git
  version: master
  name: zaton_users

- src: https://github.com/ttych/ansible_role_zdata.git
  version: master
  name: zdata

- src: https://github.com/ttych/ansible_role_zshare.git
  version: master
  name: zshare

- src: https://github.com/ttych/ansible_role_efibootmgr-hack.git
  version: master
  name: efibootmgr-hack
