---
- src: git+https://gitlab.com/ttych/ansible_role_system-base.git
  version: master
  name: system-base

- src: git+https://gitlab.com/ttych/ansible_role_freebsd-update.git
  version: master
  name: FreeBSD-update

- src: git+https://gitlab.com/ttych/ansible_role_linux-system-update.git
  version: master
  name: Linux-update

- src: git+https://gitlab.com/ttych/ansible_role_tychensky-users.git
  version: master
  name: tychensky-users

- src: git+https://gitlab.com/ttych/ansible_role_packages.git
  version: master
  name: packages

- src: git+https://github.com/ttych/ansible_role_dotfiles.git
  version: master
  name: dotfiles

- src: git+https://gitlab.com/ttych/ansible_role_canon.git
  version: master
  name: canon

- src: git+https://gitlab.com/ttych/ansible_role_zfs-customs.git
  version: master
  name: zfs-customs

- src: git+https://gitlab.com/ttych/ansible_role_grub.git
  version: master
  name: grub

- src: git+https://gitlab.com/ttych/ansible_role_network.git
  version: master
  name: network

- src: git+https://gitlab.com/ttych/ansible_role_autofs.git
  version: master
  name: autofs

- src: git+https://gitlab.com/ttych/ansible_role_ntp.git
  version: master
  name: ntp

- src: git+https://gitlab.com/ttych/ansible_role_x.git
  version: master
  name: X

- src: git+https://gitlab.com/ttych/ansible_role_clean-install.git
  version: master
  name: clean-install

- src: git+https://gitlab.com/ttych/ansible_role_keyboards.git
  version: master
  name: keyboards

# - src: git+https://github.com/ttych/ansible_role_efibootmgr-hack.git
#   version: master
#   name: efibootmgr-hack

# - src: git+https://github.com/ttych/ansible_role_services.git
#   version: master
#   name: services

# - src: git+https://github.com/ttych/ansible_role_daemontools.git
#   version: master
#   name: daemontools

# - src: git+https://github.com/ttych/ansible_role_dhcpd.git
#   version: master
#   name: dhcpd

# - src: git+https://github.com/ttych/ansible_role_network.git
#   version: master
#   name: network

- src: git+https://gitlab.com:ttych/ansible_role_FreeBSD.git
  version: master
  name: FreeBSD
