---
- name: setup
  hosts: all
  roles:
    - { role: linux-system-base, become: yes }
    - { role: linux-system-update, become: yes }
    - { role: system-users, become: yes }
    - { role: packages, become: yes }
    - { role: tychensky-users, become: yes }
    - { role: dotfiles, become: yes }
    - { role: zfs-customs, become: yes }
    - { role: autofs, become: yes }
    - { role: grub, become: yes }

    # ntpd

    # - { role: daemontools, become: yes }

    # antivirus
    # DHCP
    # DNS



    - { role: X, become: yes }
    - { role: clean-install, become: yes }
